#!/bin/bash

if [[ -f ~/.vimrc && -z "$1" ]]
then
  echo ''
  echo 'You already seem to have a ~/.vimrc file.'
  echo 'Please move this somewhere safe (or delete it) and run this command again.'
  echo ''
  exit 1
else
  ln -s ~/.vim/vimrc ~/.vimrc
  vim +PlugClean! +PlugUpdate +qall
  ~/.vim/install-plugin-update-hook.sh
fi
